# -*- coding: utf-8 -*-
"""DeepLearning_Lab1_ResNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJg7oEEHa4bf6ThaG4HJy1bDQ9wXVRUn
"""

!chmod +x /content/drive/MyDrive/Lab1/run.sh

!pip install nvcc4jupyter

# Commented out IPython magic to ensure Python compatibility.
# %load_ext nvcc4jupyter

!nvcc --version

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# for model in resnet20 resnet32
# do
#     echo "python -u trainer.py  --arch=$model  --epochs=20 --save-dir=save_$model |& tee -a log_$model"
#     python -u /content/drive/MyDrive/Lab1/trainer.py  --arch=$model  --epochs=20 --save-dir=save_$model |& tee -a log_$model
# done

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# for model in resnet44 resnet56
# do
#     echo "python -u trainer.py  --arch=$model  --epochs=20 --save-dir=save_$model |& tee -a log_$model"
#     python -u /content/drive/MyDrive/Lab1/trainer.py  --arch=$model  --epochs=20 --save-dir=save_$model |& tee -a log_$model
# done

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# for i in 1 2 3 4 5 6 7 8 9 10
# do
#   python /content/drive/MyDrive/Lab1/test_resnet20.py
# done

"""5/10"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# for i in 1 2 3 4 5 6 7 8 9 10
# do
#   python /content/drive/MyDrive/Lab1/test_resnet32.py
# done

"""7/10"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# for i in 1 2 3 4 5 6 7 8 9 10
# do
#   python /content/drive/MyDrive/Lab1/test_resnet44.py
# done

"""9/10"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# for i in 1 2 3 4 5 6 7 8 9 10
# do
#   python /content/drive/MyDrive/Lab1/test_resnet56.py
# done

"""10/10"""